# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-nbdev-ipyleaflet',
                'doc_host': 'https://tylere.github.io',
                'git_url': 'https://github.com/tylere/test-nbdev-ipyleaflet',
                'lib_path': 'test_nbdev_ipyleaflet'},
  'syms': {'test_nbdev_ipyleaflet.core': {'test_nbdev_ipyleaflet.core.foo': ('core.html#foo', 'test_nbdev_ipyleaflet/core.py')}}}
